engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
exclude_paths:
 - "bin/"
 - "logs/"
 - "plugins/"
 - "tests/"
 - "tmp/"
 - "vendor/"
 - "webroot/"
